name: Tests
on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests ğŸ§ª
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache Gradle and wrapper ğŸ—ƒï¸
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: cache-${{ runner.os }}-${{ matrix.jdk }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Validate Gradle Wrapper ğŸ”ï¸
        uses: gradle/wrapper-validation-action@v1

      - name: Run Unit tests ğŸ§ª
        run: bash ./gradlew test --stacktrace